from vpython import *

# TODO: Make graph for rod, with motional power and force power, to show that rod stores no energy. Pmot = - Pforce.

# Window settings
scene.width = 640
scene.height = 480
scene.background = color.white
scene.title = "PHY 9C Midterm Problem Start 7 \n\n"
scene.align = "none"



# Battery object
battery = cylinder(pos = vec(-3, 0, -2), axis = vec(0, 0, 1), radius = 0.2, color = color.orange)

# Connecting wires
wire1 = curve(pos = [vec(0, 0, -3), vec(-3, 0, -3), vec(-3, 0, 0)], radius = 0.05, color = color.black) # Connect top rod, battery, and upper switch
wire2 = curve(pos = [vec(-3, 0, 1), vec(-3, 0, 2), vec(0, 0, 2)], radius = 0.05, color = color.black) # Connect bottom switch and bottom rod

# Switch object, initially open
switch1 = cylinder(pos = vec(-3, 0, 1), axis = vec(0, 0, -1), radius = 0.1, color = vec(0.5, 0.5, 0.5))
switch1.rotate(axis = vec(0, 1, 0), angle = pi/6, origin = vec(-3, 0, 1))

# Conducting, frictionless rods
xMax = 15 # Prevent rod from rolling off
topRod = cylinder(pos = vec(0, 0, -3.01), axis = vec(xMax, 0, 0), radius = 0.2, color = vec(0.75, 0.50, 0.25))
bottomRod = cylinder(pos = vec(0, 0, 1.99), axis = vec(xMax, 0, 0), radius = 0.2, color = vec(0.75, 0.50, 0.25))

# Draw magnetic field
magneticField = []
for x in range(-3, 16):
    for z in range(-2, 3):
        arrow(pos = vec(x, 2, z), axis = vec(0, -4, 0), color = color.blue, opacity = 0.1, 
              shaftwidth = 0.05, headwidth = 0.10, headlength = 0.15)

# Draw main rod
rod = cylinder(pos = vec(0, 0.2 + 0.2, -3), axis = vec(0, 0, 5), radius = 0.2, color = vec(0.70, 0.40, 0.30))

# Move camera in positive x direction to center the circuit for easy viewing
scene.camera.pos = vec(xMax / 2, xMax / 4, 0)

# Calcs
refreshRate = 60
t = 0 # Total elapsed time
dt =  1.0 / refreshRate # Timestep
x = 0 # Position on screen
xTotal = 0 # Total horizontal displacement
xDot = 0 # Current velocity
switchOpen = True

# System parameters
B = 0.5 # Magnetic field strength
L = 5 # Length of center rod
m = 1 # Mass of rod
R = 5 # Resistance of rod
emf = 12 # Ideal battery emf

# Other stats
emfInduced = 0 # emf induced on rod by Faraday's Law
current = 0 # Current in rod, positive when going down rod
Ubat = 0 # Total energy generated by battery
Uemf = 0 # Total energy dissipated by motional emf
Ures = 0 # Total energy dissipated by resistance in rod

# Display stats on top of scene
# Set up stats display on top of scene
scene.append_to_title("Horizontal displacement: ")
xText = wtext(text = '{:.3f}'.format(0), pos = scene.title_anchor)
scene.append_to_title(" m \n")
scene.append_to_title("Velocity: ")
xDotText = wtext(text = '{:.3f}'.format(0), pos = scene.title_anchor)
scene.append_to_title(" m/s \n")
scene.append_to_title("Acceleration: ")
xDotDotText = wtext(text = '{:.3f}'.format(0), pos = scene.title_anchor)
scene.append_to_title(" m/s<sup>2</sup> \n\n")

scene.append_to_title("Motional emf: ")
emfInducedText = wtext(text = '{:.3f}'.format(emfInduced), pos = scene.title_anchor)
scene.append_to_title(" V \n")
scene.append_to_title("Current through rod downward: ")
currentText = wtext(text = '{:.3f}'.format(current), pos = scene.title_anchor)
scene.append_to_title(" A \n\n")

scene.append_to_title("Magnetic field strength: ", '{:.3f}'.format(B), "T \n")
scene.append_to_title("Rod length: ", '{:.3f}'.format(L), "m \n")
scene.append_to_title("Rod mass: ", '{:.3f}'.format(m), "kg \n")
scene.append_to_title("Rod resistance: ", '{:.3f}'.format(R), "ohm \n")
scene.append_to_title("Battery emf: ", '{:.3f}'.format(emf), "V \n\n")


# Set up velocity graph over time
g1 = graph(title = "Velocity graph", xtitle = "Time (s)", ytitle = "Velocity (m/s)", scroll = True, xmin = 0, xmax = 5)
velocity = gcurve(color = color.black, label = "v")

# Energy graph over time?
# Do power instead lol
# Power generated by battery Pbat = i * emf, when switch is closed. Switch open, Pbat = 0.
# Power from force on rod Pforce = F * v = m * xDotDot * xDot
# Power dissipated by motional emf Pmot = -i * emfMotional
# Power dissipated by resistance in rod Pres = -(i^2) * R
# Hopefully Ptot = 0?
g2 = graph(title = "Power graph", xtitle = "Time (s)", ytitle = "Watts (W)", scroll = True, xmin = 0, xmax = 5)

#forcePower = gcurve(color = color.red, label = "P<sub>force</sub>")
batteryPower = gcurve(color = color.green, label = "P<sub>bat</sub>")
motionalPower = gcurve(color = color.blue, label = "P<sub>mot</sub>")
resistorPower = gcurve(color = color.purple, label = "P<sub>res</sub>")
power = gcurve(color = color.black, label = "P<sub>total</sub>")


# Pause button, taken from double pendulum example on vpython web
run = False # Program starts paused
def pause(btn):
    global run
    run = not run # Toggle run
    # Update button text
    if run:
        btn.text = "Pause"
    else:
        btn.text = "Resume"
pauseBtn = button(text = "Resume", bind = pause, pos = scene.title_anchor) # Create pause button

# Button to toggle switch
def toggleSwitch(btn):
    global switchOpen
    # Update button text
    if (switchOpen): # Close switch
        btn.text = "Open switch"
        switch1.rotate(axis = vec(0, 1, 0), angle = -pi/6, origin = vec(-3, 0, 1))
    else: # Open switch
        btn.text = "Close switch"
        switch1.rotate(axis = vec(0, 1, 0), angle = pi/6, origin = vec(-3, 0, 1))
    switchOpen = not switchOpen # Toggle boolean
toggleSwitchBtn = button(text = "Close switch", bind = toggleSwitch, pos = scene.title_anchor)

def reset():
    global switchOpen, toggleSwitchBtn, x, xTotal, xDot, rod, velocity, g1, t
    global power, batteryPower, motionalPower, resistorPower
    # Open switch if necessary
    if (not switchOpen):
        switch1.rotate(axis = vec(0, 1, 0), angle = pi/6, origin = vec(-3, 0, 1))
        switchOpen = True
        toggleSwitchBtn.text = "Close switch"
    # Reset rod position
    x = 0
    xTotal = 0
    xDot = 0
    rod.pos = vec(0, 0.2 + 0.2, -3)
    # Reset time
    t = 0
    # Reset graphs
    g1.xmin = 0
    g1.xmax = 5
    g2.xmin = 0
    g2.xmax = 5
    velocity.data = []
    power.data = []
    #forcePower.data = []
    batteryPower.data = []
    motionalPower.data = []
    resistorPower.data = []
    # Reset stats display
    xText.text = '{:.3f}'.format(0)
    xDotText.text = '{:.3f}'.format(0)
    xDotDotText.text = '{:.3f}'.format(0)
    emfInducedText.text = '{:.3f}'.format(0)
    currentText.text = '{:.3f}'.format(0)

resetBtn = button(text = "Reset", bind = reset, pos = scene.title_anchor)

# Animation loop
while True:
    rate(refreshRate) # Needed for smooth animation
    if not run: continue # Skip animation when paused
    
    # Maybe try Verlet integration instead? Just for fun
    # Calculate dx
    dxDot = 0 # Infinitesimal change in velocity
    if (switchOpen):
        dxDot = -((B**2 * L**2)/(m*R))*xDot*dt
    else:
        dxDot = (B*L/(m*R))*(emf - xDot*B*L)*dt
    xDot += dxDot # Change current velocity
    dx = xDot * dt # Infinitesimal change in x
    x += dx # Change current x
    xTotal += dx # Increment total displacement
    rod.pos += vec(dx, 0, 0) # Move rod to new position
    # Set rod back if too far away, keep total displacement xTotal
    if (x > xMax):
        rod.pos -= vec(xMax, 0, 0)
        x -= xMax
    # Update graph
    xDotDot = dxDot / dt # Current acceleration
    emfInduced = xDot * B * L
    if (switchOpen):
        current = -emfInduced / R
    else:
        current = (emf - emfInduced) / R
   
    # Power generated by battery Pbat = i * emf, when switch is closed. Switch open, Pbat = 0.
    # Power dissipated by motional emf Pmot = -i * emfMotional
    # Power dissipated by resistance in rod Pres = -(i^2) * R
    # Hopefully Ptot = 0?
    # Positive, power generated. Negative, power dissipated.
    Pbat = current * emf
    if (switchOpen):
        Pbat = 0
    #Pforce = m * xDotDot * xDot # Power dissipated from motional emf is converted into kinetic energy of the rod
    Pmot = -current * emfInduced
    Pres = -(current**2) * R # Resistor always dissipates energy
    Ptot = Pbat + Pmot + Pres # Total energy of system

    velocity.plot(t, xDot)  
    batteryPower.plot(t, Pbat)
    #forcePower.plot(t, Pforce)  
    motionalPower.plot(t, Pmot)
    resistorPower.plot(t, Pres)
    power.plot(t, Ptot)

    # Update stats
    xText.text = '{:.3f}'.format(xTotal)
    xDotText.text = '{:.3f}'.format(xDot)
    xDotDotText.text = '{:.3f}'.format(xDotDot)
    emfInducedText.text = '{:.3f}'.format(emfInduced)
    currentText.text = '{:.3f}'.format(current)

    t += dt # Increment elapsed time